### ISSUE TITLE
Proposal: Add a browser mode

### ISSUE THREAD

**Issue by toonsevrin** [OrchidTechnologies/orchid#39] opened 2020-04-09 01:21 UTC
I believe the Orchid app should have a Tor like browser integrated. 

A VPN is not that useful from a privacy perspective if all our personal data from say, facebook/google play/..., is still routed through the exit node.

Ideally I want to be able to say, look, only what I do in this browser should go over the vpn. A simple whitelist/blacklist for apps would thus work as well.

**Comment by toonsevrin** [comment] 2020-04-09 11:38
You could take a look at the app Orbot for some inspiration (tor app on android)

**Comment by toonsevrin** [comment] 2020-04-09 11:40
The second nice thing would be that you could use a separate circuit for each app under the hood.

**Comment by saurik** [comment] 2020-04-18 11:19
So as much as I appreciate the sentiment, I personally believe that building and maintaining a browser is out of scope for this project: there is a lot of work to a privacy-preserving browser, and that is being handled well by the Tor group; maybe at some point the Tor project--or something from the cryptocurrency ecosystem, such as Brave--would find Orchid interesting enough to integrate into their browser, but at this time I don't think it makes sense to maintain such a concept for Orchid.

(I will say, though, that for our primary attacker model--a local ISP that you don't trust--I highly recommend you take all of your traffic and send it to more neutral parties, absolutely including your Facebook/Google Play traffic... like, that seems really important for you to remove from the prying eyes of your local ISP.)

As for your second comment about using a "separate circuit for each app", that is definitely a feature that is on our roadmap, but given that there's not much to say on that and that the title of this issue is really about a "browser mode", I'm going to go ahead and close this issue (as opposed to keeping it open to try to track some concept of completion on "separate circuits", particularly as having an issue open for that really isn't necessary anyway).

Regardless, thanks for the thoughts!!!

**Closed by saurik** 2020-04-18 11:19 UTC

**Comment by toonsevrin** [comment] 2020-04-18 11:42
Having orchid as an alternative circuit provider to the tor network in privacy preserving browsers (eg. the tor browser) is a cool concept, perhaps the better thing to put on a roadmap is to provide a patch/extension to these browsers that provides this functionality.

Anyways, my ISP scraping the little Facebook metadata they can get is really not within my threat model hahaha

**Comment by saurik** [comment] 2020-04-18 15:41
So, the issue is that your ISP isn't always someone like Cox/Comcast, but is sometimes "a random friend or family member", "the owner or manager of the local coffee shop", or "the person who set up a Wi-Fi access point with the same SSID as the one you have at home"; and like, it doesn't end there, as your local network segment isn't really all _that_ secure (as people might have heard your Wi-Fi password once, or someone might have temporary physical access to one of your routers).
